POST https://nodejs-begginer-course-rocketseat.onrender.com/videos
Content-type: application/json

{
  "title": "Video carlos",
  "description": "video para o carlos",
  "duration": 180
}

###

GET  https://nodejs-begginer-course-rocketseat.onrender.com/videos?search=node

###

PUT https://nodejs-begginer-course-rocketseat.onrender.com/videos/23331ee0-5e72-4937-b272-e8e8d6a0d1a9
Content-type: application/json

{
  "title": "Video 02",
  "description": "Esse é o primeiro vídeo",
  "duration": 180
}

###

DELETE https://nodejs-begginer-course-rocketseat.onrender.com/videos/2c963f0d-971c-4738-836e-78fc150953b9